### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by chtinahow**

### CODE REVIEW

**Comment by retrogamer80s** [comment]
Hi,

I can't make it in to see you both today so can you give me a status of the card design?

Thanks,
Steph

**Comment by MukeytheMuse** [comment]
Hello! This is Kimberly. The card designs have been completed. Right now,
we're gonna work off of them to create a rough draft of the layout on
Xcode. I actually did get started on it on Friday, but I lost those files
somehow. But, the prototype is coming along. We're also doing more tutorial
with SpriteKit as well. ^^

**Comment by MukeytheMuse** [comment]
Also, we still need input from the visually impaired students. I believe
that's all for now.

**Comment by retrogamer80s** [comment]
Ok, thank you.  

Steph

**Comment by retrogamer80s** [comment]
Ok.  For that part we will want some screenshots to show them.

Steph

**Comment by piperchester** [comment]
Doc update's been added to dev. Closing PR. Thanks!

**Pull request closed without merging**
