### PR TITLE
Summer Release v0.2

### PR DESCRIPTION
**Pull request by 7imbrook**
### Final Checks and Documentation

Documentation for this project can be found on our google drive http://goo.gl/xVYdES (collaborators only)
- [ ] Tests
- [ ] Design Rationale
- [ ] Class Descriptions
- [ ] Class UML
- [x] Update Requirements
- [x] Dead code removal*
### Features not in Development
- [ ] Search (merge in the feature/search branch when finished)

### CODE REVIEW

**Comment by 7imbrook** [comment]
Why was this closed? Are we making a new one?

**Comment by piperchester** [comment]
Let's make a new one on Monday with the updates from Ludi

**Comment by 7imbrook** [comment]
Alright, I move in Monday. Can we do that Tuesday?

**Comment by piperchester** [comment]
Sure :+1:
ᐧ

On Sat, Jan 17, 2015 at 9:41 AM, Michael Timbrook notifications@github.com
wrote:

> Alright, I move in Monday. Can we do that Tuesday?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RITAccess/accessmath/pull/124#issuecomment-70369300.

## 

_Piper W. Chester_
BS Software Engineering '16
pwc1203@rit.edu _|_ (607) 661 - 2259

**Pull request closed without merging**
